version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: modulo-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    command: redis-server --appendonly yes
    networks:
      - modulo-network-local

  mysql:
    image: mysql:8.0
    container_name: modulo-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modulo-db
      MYSQL_USER: modulo
      MYSQL_PASSWORD: modulo1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_local:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - modulo-network-local

networks:
  modulo-network-local:
    driver: bridge

volumes:
  redis_data_local:
  mysql_data_local: