services:
  app:
    image: kwonyonghyun/modulo:${IMAGE_TAG}
    container_name: modulo-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/modulo-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=modulo
      - SPRING_DATASOURCE_PASSWORD=modulo1234
      - OAUTH2_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OAUTH2_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=${AWS_SECRET_KEY}
      - CLOUD_AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - CLOUD_AWS_REGION_STATIC=${AWS_REGION}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - SWAGGER_USERNAME=${SWAGGER_USERNAME}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
    depends_on:
      - mysql
      - redis
    networks:
      - modulo-network-dev

  mysql:
    image: mysql:8.0
    container_name: modulo-mysql-dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=modulo-db
      - MYSQL_USER=modulo
      - MYSQL_PASSWORD=modulo1234
    volumes:
      - mysql_data_dev:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - modulo-network-dev

  redis:
    image: redis:latest
    container_name: modulo-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    networks:
      - modulo-network-dev

networks:
  modulo-network-dev:
    driver: bridge

volumes:
  mysql_data_dev:
  redis_data_dev: