version: '3.8'
services:
  app:
    build: .
    container_name: modulo-app-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - redis
    networks:
      - modulo-network-local

  redis:
    image: redis:latest
    container_name: modulo-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    command: redis-server --appendonly yes
    networks:
      - modulo-network-local

networks:
  modulo-network-local:
    driver: bridge

volumes:
  redis_data_local: