spring:
  datasource:
    url: jdbc:mysql://dev-db:3306/modulo_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  redis:
    host: dev-redis
    port: 6379

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://dev-api.modulo.com/api/auth/login/google/callback

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    header: Authorization
    expiration: 3600000
  refresh:
    header: Refresh-Token
    expiration: 1209600000

client:
  url: https://dev.modulo.com