spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: dGVzdC1qd3Qtc2VjcmV0LWtleS1mb3ItbW9kdWxvLXByb2plY3QtdGVzdC1lbnZpcm9ubWVudAo=
  token-validity-in-seconds: 3600